apiVersion: skaffold/v2alpha3
kind: Config
deploy:
  kubectl:
    manifests:
      - ./infra/k8s/*
      - ./infra/k8s-dev/*
build:
  local:
    push: true
  artifacts:
    - image: bk7987/vend-auth
      context: auth
      docker:
        dockerfile: Dockerfile
      sync:
        manual:
          - src: "src/**/*.ts"
            dest: .
    - image: bk7987/vend-user
      context: user
      docker:
        dockerfile: Dockerfile
      sync:
        manual:
          - src: "src/**/*.ts"
            dest: .
    - image: bk7987/vend-review
      context: review
      docker:
        dockerfile: Dockerfile
      sync:
        manual:
          - src: "src/**/*.cs"
            dest: .
