apiVersion: apps/v1
kind: Deployment
metadata:
  name: auth-depl
spec:
  replicas: 1
  selector:
    matchLabels:
      app: auth
  template:
    metadata:
      labels:
        app: auth
    spec:
      containers:
        - name: auth
          image: bk7987/vend-auth
          env:
            - name: MONGO_URI
              value: "mongodb://auth-db-srv:27017/auth"
            - name: PORT
              value: "3000"
            - name: FIREBASE_CONFIG
              valueFrom:
                secretKeyRef:
                  name: firebase-admin-credentials
                  key: FIREBASE_CONFIG
---
apiVersion: v1
kind: Service
metadata:
  name: auth
spec:
  selector:
    app: auth
  ports:
    - name: auth
      protocol: TCP
      port: 3000
      targetPort: 3000
